name: Install Methods

on:
  schedule:
    - cron: '0 6 * * 1'
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions: {}

# When a PR is updated, cancel the jobs from the previous version. Merges
# do not define head_ref, so use run_id to never cancel those jobs.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  conda-pip:
    name: conda + pip
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5 # v4.0.1
        with:
          python-version: "3.12"
          activate-environment: install-test
          channels: conda-forge
          channel-priority: strict
          conda-remove-defaults: true
      - run: conda install -y gdal
      - run: pip install .[implementations]
      - run: python -c "import openeo_processes_dask; print('OK')"

  micromamba-pip:
    name: micromamba + pip
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476 # v3.0.0
        with:
          environment-name: install-test
          create-args: python=3.12 gdal
      - run: pip install .[implementations]
      - run: python -c "import openeo_processes_dask; print('OK')"

  system-pip:
    name: system packages + pip
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - run: sudo apt-get update && sudo apt-get install -y gdal-bin libgdal-dev
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.12"
      - run: pip install "gdal==$(gdal-config --version)" .[implementations]
      - run: python -c "import openeo_processes_dask; print('OK')"
